name: sijunjung_go_fe
description: A multi-app project for on-demand service (Customer, Driver, Merchant)
publish_to: 'none'  # Not publishing to pub.dev

# Menempatkan environment di bagian atas
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependensi bersama untuk aplikasi Customer, Driver, Merchant
  firebase_core: ^4.4.0
  provider: ^6.0.3
  google_maps_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
