name: shared
description: Shared code for all apps
publish_to: "none"
# Menambahkan SDK constraint untuk mendukung Null Safety
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  # Dependensi yang digunakan bersama, jika ada
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
